import { GlobalState } from '@/types';

export const initialMockData: GlobalState = {
  tutors: [
    {
      id: 't1',
      name: 'Ayesha Siddiqui',
      avatar: 'https://i.pravatar.cc/150?u=ayesha',
      subjects: ['Mathematics', 'Physics'],
      qualifications: ['MSc Physics, NUST Islamabad', '6+ years tutoring experience'],
      rate: 1200,
      rating: 4.9,
      reviewsCount: 134,
      isFeatured: true,
      bio: 'I specialize in making Mathematics and Physics easy to understand. My proven 5-step method guarantees a grade improvement for every student.',
      status: 'approved',
      city: 'Islamabad',
      online: true,
      responseTime: 'within 1 hour',
      experienceYears: 6,
      languages: ['Urdu', 'English'],
      studentsTaught: 420,
      mode: 'both',
    },
    {
      id: 't2',
      name: 'Bilal Ahmed Qureshi',
      avatar: 'https://i.pravatar.cc/150?u=bilal',
      subjects: ['Computer Science', 'Web Development', 'React'],
      qualifications: ['Senior Software Engineer @ Systems Ltd', 'BSc CS, FAST NUCES Lahore'],
      rate: 1800,
      rating: 5.0,
      reviewsCount: 97,
      isFeatured: true,
      bio: 'Learn coding from an industry professional. I focus on React, Node.js and real-world projects that will get you hired at top Pakistani tech companies.',
      status: 'approved',
      city: 'Lahore',
      online: true,
      responseTime: 'within 2 hours',
      experienceYears: 5,
      languages: ['Urdu', 'English'],
      studentsTaught: 260,
      mode: 'online',
    },
    {
      id: 't3',
      name: 'Fatima Zahra Malik',
      avatar: 'https://i.pravatar.cc/150?u=fatima',
      subjects: ['English Literature', 'IELTS', 'Communication Skills'],
      qualifications: ['MA English, University of Punjab Lahore', 'IELTS Score 8.5'],
      rate: 900,
      rating: 4.8,
      reviewsCount: 218,
      isFeatured: true,
      bio: 'Expert in IELTS preparation and English communication. My immersive approach builds fluency and confidence that gets students their target band scores.',
      status: 'approved',
      city: 'Lahore',
      online: true,
      responseTime: 'within 30 mins',
      experienceYears: 9,
      languages: ['English', 'Urdu', 'Punjabi'],
      studentsTaught: 640,
      mode: 'both',
    },
    {
      id: 't4',
      name: 'Usman Tariq',
      avatar: 'https://i.pravatar.cc/150?u=usman',
      subjects: ['Chemistry', 'Biology', 'MDCAT Prep'],
      qualifications: ['MBBS Student, AIMC Lahore', 'MDCAT Score 185/200'],
      rate: 1500,
      rating: 4.7,
      reviewsCount: 42,
      isFeatured: false,
      bio: 'Helping students ace MDCAT and FSc exams. Chemistry and Biology are my passion, and I love making these subjects approachable and exciting.',
      status: 'approved',
      city: 'Faisalabad',
      online: false,
      responseTime: 'within 3 hours',
      experienceYears: 3,
      languages: ['Urdu', 'English'],
      studentsTaught: 130,
      mode: 'both',
    },
    {
      id: 't5',
      name: 'Sara Imran',
      avatar: 'https://i.pravatar.cc/150?u=saraimran',
      subjects: ['Mathematics', 'Statistics', 'A-Levels'],
      qualifications: ['MSc Mathematics, QAU Islamabad', 'A-Level Specialist, 8 years experience'],
      rate: 1400,
      rating: 4.9,
      reviewsCount: 178,
      isFeatured: false,
      bio: 'Dedicated math tutor with a passion for turning confusion into clarity. A-Level and FSc students consistently achieve A grades under my guidance.',
      status: 'approved',
      city: 'Islamabad',
      online: true,
      responseTime: 'within 1 hour',
      experienceYears: 8,
      languages: ['English', 'Urdu'],
      studentsTaught: 510,
      mode: 'online',
    },
    {
      id: 't6',
      name: 'Hamid Raza',
      avatar: 'https://i.pravatar.cc/150?u=hamidraza',
      subjects: ['Physics', 'Engineering', 'ECAT Prep'],
      qualifications: ['BSc Electrical Engineering, UET Lahore', 'ECAT Score 98th Percentile'],
      rate: 1600,
      rating: 4.8,
      reviewsCount: 89,
      isFeatured: false,
      bio: 'UET graduate helping students crack ECAT and master Physics. My problem-solving focused approach makes complex concepts click instantly.',
      status: 'approved',
      city: 'Lahore',
      online: true,
      responseTime: 'within 2 hours',
      experienceYears: 4,
      languages: ['Urdu', 'English', 'Punjabi'],
      studentsTaught: 200,
      mode: 'both',
    },
    {
      id: 't7',
      name: 'Mahnoor Abbasi',
      avatar: 'https://i.pravatar.cc/150?u=mahnoor',
      subjects: ['Accounting', 'Economics', 'Business Studies'],
      qualifications: ['ACCA Affiliate', 'BBA, IBA Karachi'],
      rate: 1300,
      rating: 4.9,
      reviewsCount: 156,
      isFeatured: false,
      bio: 'ACCA-qualified tutor making Accounting and Economics intuitive for O/A-Level and BBA students. I focus on exam technique and real-world examples.',
      status: 'approved',
      city: 'Karachi',
      online: true,
      responseTime: 'within 1 hour',
      experienceYears: 7,
      languages: ['English', 'Urdu'],
      studentsTaught: 380,
      mode: 'online',
    },
    {
      id: 't8',
      name: 'Imran Shah',
      avatar: 'https://i.pravatar.cc/150?u=imranshah',
      subjects: ['Islamic Studies', 'Urdu', 'Quran'],
      qualifications: ['MA Islamic Studies, IIUI Islamabad', 'Hafiz-e-Quran'],
      rate: 800,
      rating: 5.0,
      reviewsCount: 203,
      isFeatured: false,
      bio: 'Patient and structured Quran, Tajweed and Islamiat tutor for all ages. Trusted by families across Pakistan for online and home tuition.',
      status: 'approved',
      city: 'Peshawar',
      online: true,
      responseTime: 'within 30 mins',
      experienceYears: 10,
      languages: ['Urdu', 'Pashto', 'Arabic'],
      studentsTaught: 720,
      mode: 'both',
    },
  ],
};
