import { GlobalState } from '@/types';

export const initialMockData: GlobalState = {
  tutors: [
    {
      id: 't1',
      name: 'Ayesha Siddiqui',
      avatar: 'https://i.pravatar.cc/150?u=ayesha',
      subjects: ['Mathematics', 'Physics'],
      qualifications: ['MSc Physics, NUST Islamabad', '6+ years tutoring experience'],
      rate: 1200,
      rating: 4.9,
      reviewsCount: 134,
      isFeatured: true,
      bio: 'I specialize in making Mathematics and Physics easy to understand. My proven 5-step method guarantees a grade improvement for every student.',
      status: 'approved',
    },
    {
      id: 't2',
      name: 'Bilal Ahmed Qureshi',
      avatar: 'https://i.pravatar.cc/150?u=bilal',
      subjects: ['Computer Science', 'Web Development', 'React'],
      qualifications: ['Senior Software Engineer @ Systems Ltd', 'BSc CS, FAST NUCES Lahore'],
      rate: 1800,
      rating: 5.0,
      reviewsCount: 97,
      isFeatured: true,
      bio: 'Learn coding from an industry professional. I focus on React, Node.js and real-world projects that will get you hired at top Pakistani tech companies.',
      status: 'approved',
    },
    {
      id: 't3',
      name: 'Fatima Zahra Malik',
      avatar: 'https://i.pravatar.cc/150?u=fatima',
      subjects: ['English Literature', 'IELTS', 'Communication Skills'],
      qualifications: ['MA English, University of Punjab Lahore', 'IELTS Score 8.5'],
      rate: 900,
      rating: 4.8,
      reviewsCount: 218,
      isFeatured: true,
      bio: 'Expert in IELTS preparation and English communication. My immersive approach builds fluency and confidence that gets students their target band scores.',
      status: 'approved',
    },
    {
      id: 't4',
      name: 'Usman Tariq',
      avatar: 'https://i.pravatar.cc/150?u=usman',
      subjects: ['Chemistry', 'Biology', 'MDCAT Prep'],
      qualifications: ['MBBS Student, AIMC Lahore', 'MDCAT Score 185/200'],
      rate: 1500,
      rating: 4.7,
      reviewsCount: 42,
      isFeatured: false,
      bio: 'Helping students ace MDCAT and FSc exams. Chemistry and Biology are my passion, and I love making these subjects approachable and exciting.',
      status: 'approved',
    },
    {
      id: 't5',
      name: 'Sara Imran',
      avatar: 'https://i.pravatar.cc/150?u=saraimran',
      subjects: ['Mathematics', 'Statistics', 'A-Levels'],
      qualifications: ['MSc Mathematics, QAU Islamabad', 'A-Level Specialist, 8 years experience'],
      rate: 1400,
      rating: 4.9,
      reviewsCount: 178,
      isFeatured: false,
      bio: 'Dedicated math tutor with a passion for turning confusion into clarity. A-Level and FSc students consistently achieve A grades under my guidance.',
      status: 'approved',
    },
    {
      id: 't6',
      name: 'Hamid Raza',
      avatar: 'https://i.pravatar.cc/150?u=hamidraza',
      subjects: ['Physics', 'Engineering', 'ECAT Prep'],
      qualifications: ['BSc Electrical Engineering, UET Lahore', 'ECAT Score 98th Percentile'],
      rate: 1600,
      rating: 4.8,
      reviewsCount: 89,
      isFeatured: false,
      bio: 'UET graduate helping students crack ECAT and master Physics. My problem-solving focused approach makes complex concepts click instantly.',
      status: 'approved',
    },
  ],
};
